### ISSUE TITLE
Weather station - recommended settings

### ISSUE THREAD

**Issue by Eldenroot** [vodnik12/JWA_BME280#10]
Hi,

I use Adafruit BME280 library, but ti returns not accurate results from measurements (some drift in pressure, mainly). I use default normal mode, no filter, measurement every 4 sec.

Anyway I have read that it could be caused by library itself so I would like to use your library with official driver inside. 

Do you have any recommendations for this purpose? IC2 is supported?

Thank you!

**Comment by janw-cz** [comment]
Hi,
stability of BME2800 readings is sometimes magical. With this driver the stability used to be ok after first couple of seconds.

I2C is supported, see example which comes with the library. SPI is also supported, see beginSPI(...) in Bme280BoschWrapper.h 

Have fun with BME280 :-)
