### ISSUE TITLE
Bosch driver 3.5.0 update?

### ISSUE THREAD

**Issue by stef-ladefense** [vodnik12/JWA_BME280#14]
https://github.com/BoschSensortec/BME280_driver/releases

merci

**Comment by janw-cz** [comment]
Upgraded

**Comment by stef-ladefense** [comment]
oups...

C:\Users\stephane\Documents\Arduino\libraries\JWA_BME280-master\Bme280BoschWrapper.cpp: In member function 'void Bme280BoschWrapper::I2CInit()':
C:\Users\stephane\Documents\Arduino\libraries\JWA_BME280-master\Bme280BoschWrapper.cpp:106:19: error: invalid conversion from 'void (*)(uint32_t) {aka void (*)(unsigned int)}' to 'bme280_delay_us_fptr_t {aka void (*)(unsigned int, void*)}' [-fpermissive]
   bme280.delay_us = Bme280BoschWrapper::delaymsec;
                   ^
C:\Users\stephane\Documents\Arduino\libraries\JWA_BME280-master\Bme280BoschWrapper.cpp: In member function 'void Bme280BoschWrapper::SPIInit()':
C:\Users\stephane\Documents\Arduino\libraries\JWA_BME280-master\Bme280BoschWrapper.cpp:116:19: error: invalid conversion from 'void (*)(uint32_t) {aka void (*)(unsigned int)}' to 'bme280_delay_us_fptr_t {aka void (*)(unsigned int, void*)}' [-fpermissive]
   bme280.delay_us = Bme280BoschWrapper::delaymsec;

**Comment by stef-ladefense** [comment]
i found folk in ver 3.5 working
https://github.com/h2zero/JWA_BME280

**Comment by janw-cz** [comment]
Should be better now. The error did not show up in my Arduino, weird.

**Comment by stef-ladefense** [comment]
it's work now for me
thk Jan
