### ISSUE TITLE
Incorrect pressure  value 

### ISSUE THREAD

**Issue by soosp** [vodnik12/JWA_BME280#4]
The pressure value is not in the correct range after upgrading to 3.3.4 driver.

Code:
```
p = sensor.getPressure() / 100.0F;
Serial.print("Debug pressuere: ");
Serial.print(p);
Serial.println(" hPa");
```

Result:
`Debug pressuere: 99035.32 hPa`

It should be:
`Debug pressuere: 990.35 hPa`

**Comment by janw-cz** [comment]
It really was incorrect. I forgot to switch off 64-bit calculation of pressure, this was a side effect. I have now committed switch to 32-bit calculation which fixes this issue.

**Comment by soosp** [comment]
Thank you,
I tested it on my project and it works well.
