### ISSUE TITLE
Pressure output is in 1/100 Pa, and not Pa

### ISSUE THREAD

**Issue by JacquesBB** [vodnik12/JWA_BME280#5]
Thanks Jan for your effort. 

I appreciate a lot that it uses  the unchanged Bosch library. 

But it seems to me that  contrary to your example,  the output is in 1/100th of Pa, and not Pa. 

The normal atmospheric pressure is about 1035 mbar = 1035 hPa = 103500Pa
and not 10350000 Pa, as in your output. 

Best Wishes 
Jacques

**Comment by janw-cz** [comment]
Hi  Jacques,

there was a bug in my library when I upgraded to latest BME280 driver. Are
you using the latest version of my library from github?

Have a nice day,
Jan

Dne so 21. 4. 2018 21:50 uživatel JacquesBB <notifications@github.com>
napsal:
